Item 9092: Naming pattern improvements
LabKey/labkey-api-js pull request #118
Opened 2021-12-15 18:02 UTC by XingY

#### Rationale
Utils to support naming pattern validations and previews

#### Related Pull Requests
* 

#### Changes
* Add validateNameExpressions, getDomainNamePreviews methods to Domain

2021-12-16 20:36 UTC, labkey-susanh approved these changes
Minor comments.  No need for re-review, though.

2021-12-16 20:36 UTC, labkey-susanh commented on src/labkey/Domain.ts
> +        failure: getCallbackWrapper(getOnFailure(options), options.scope, true),
Is `scope` meant to be added to options when parsing the `arguments` array?  I guess this isn't done in other methods that use this pattern, but I'm unclear when the `arguments` option is used and how people know what order to provide those arguments.

2021-12-16 20:36 UTC, labkey-susanh commented on src/labkey/Domain.ts
> +export function getDomainNamePreviews(config: GetDomainDetailsOptions): XMLHttpRequest {
Probably should have some docs on this since it's exported.

2021-12-16 20:36 UTC, labkey-susanh commented on src/labkey/Domain.ts
> +    } : config;
Ok, really don't know how the order of these arguments is determined.  What am I missing?

2021-12-17 04:29 UTC, labkey-nicka requested changes

2021-12-17 04:29 UTC, labkey-nicka commented on src/labkey/Domain.ts
> +    let options: ValidateDomainNameExpressionOptions = arguments.length > 1 ? {
Is this configuration necessary? We only do this for cases where we are providing backwards compatibility for methods that formerly took multiple parameters and now take a configuration object. I would recommend removing this for these new methods.

2021-12-20 17:59 UTC, labkey-nicka commented on src/labkey/Domain.ts
> +    let options: ValidateDomainNameExpressionOptions = arguments.length > 1 ? {
@XingY Thanks for adjusting. Looks good.

2021-12-20 18:02 UTC, labkey-nicka approved these changes

2021-12-23 15:50 UTC, merged