Enable data region filtration based on Ontology concepts and hierarchy
LabKey/labkey-api-js pull request #96
Opened 2021-04-21 18:42 UTC by labkey-ians

#### Rationale
Item #8670 - https://docs.google.com/document/d/1QmHYktA4uNPxiSeid1kX2TakE2E0QPU4ZBkuSwTNeZI/edit?usp=sharing
Ontology, data region column filtering

#### Related Pull Requests
* https://github.com/LabKey/platform/pull/2205

#### Changes
* Added Filter.Types.ONTOLOGY_NOT_IN_SUBTREE and Filter.Types.ONTOLOGY_IN_SUBTREE

2021-04-22 15:09 UTC, cnathe requested changes
There is an empty file `Ontology.ts` in this PR is that needed or can it be removed?

2021-04-22 15:09 UTC, cnathe commented on CHANGELOG.md
> +## 1.3.TBD - TBD
I assume that this would be a minor version bump to 1.4.0 since it is adding new functionality.

2021-04-22 15:09 UTC, cnathe commented on src/labkey/filter/Types.ts
> +    ONTOLOGY_NOT_IN_SUBTREE : registerFilterType("Is Not In Subtree", null, "concept:notinsubtree", true,)
minor: extra comma after the last param in `registerFilterType()` for both of these.

2021-04-22 16:32 UTC, labkey-nicka requested changes, later dismissed
@labkey-ians you'll need to update the `filter_types_snapshot.json` to get the tests passing. This is a snapshot that helps to ensure there are no accidental modifications of our filter types. I'd recommend taking a look at the test failure to ensure that all the values for these new types are as you expect. After that you can follow the steps in `Types.spec.ts` to get updated JSON which can be used to update the `filter_types_snapshot.json`.

2021-04-28 14:50 UTC, cnathe approved these changes

2021-05-01 19:41 UTC, merged